# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # Runs a CLI scan from Github
      # - name: Checkmarx Scan
  # You may pin to the exact commit or the version.
  # uses: checkmarx-ts/checkmarx-github-action@bb9101ed82fa9485fe5c6677f5608c3a8c077f25
  # uses: checkmarx-ts/checkmarx-github-action@v1.0.3
  # with:
    # Checkmarx CLI Action
    # cxAction: Scan # optional, default is Scan
    # Checkmarx Version
    # cxVersion: 9.2 # optional, default is 8.9
    # IP address or resolvable name of CxSAST web server.
    # cxServer: https://cxflowsls.ngrok.io   # default is https://cxflowsls.ngrok.io
    # Checkmarx Username
    # cxUsername: admin # default is first.last@company.com
    # Checkmarx Token
    # cxPassword: Cx!234567 # default is 
    # Checkmarx Team
    # cxTeam: \CxServer # default is 
    # Checkmarx Project Name
 # Coverity configuration file.
# The schema is available here: <install-dir>/doc/configuration-schema.json

# Specifies where the analysis results should be sent.
commit:

  # Coverity Connect configuration to use when committing defects to Coverity
  # Connect.
  connect:

    # The name of the stream to commit the results to.
    stream: sls-bodgeit-master

    # Absolute URL of where to commit the Coverity Connect results.
    # url: https://testing.coverity.synopsys.com:443
    url: https://poc391.coverity.synopsys.com 
     



