# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # Runs a CLI scan from Github
      - name: Checkmarx Scan
  # You may pin to the exact commit or the version.
  # uses: checkmarx-ts/checkmarx-github-action@bb9101ed82fa9485fe5c6677f5608c3a8c077f25
  uses: checkmarx-ts/checkmarx-github-action@v1.0.3
  with:
    # Checkmarx CLI Action
    cxAction: Scan # optional, default is Scan
    # Checkmarx Version
    cxVersion: 9.2 # optional, default is 8.9
    # IP address or resolvable name of CxSAST web server.
    cxServer: https://cxflowsls.ngrok.io   # default is https://cxflowsls.ngrok.io
    # Checkmarx Username
    cxUsername: admin # default is first.last@company.com
    # Checkmarx Token
    cxToken: # optional, default is 
    # Checkmarx Password
    cxPassword: Cx!234567 # default is 
    # Checkmarx Team
    cxTeam: \CxServer # default is 
    # Checkmarx Project Name
    cxProject: # optional, default is 
    # If not provided, will use preset defined in existing project or, for a new project, the default preset.
    cxPreset: # optional, default is Checkmarx Default
    # Threshold for High Severity Vulnerabilities
    cxHigh: # optional, default is -1
    # Threshold for Medium Severity Vulnerabilities
    cxMedium: # optional, default is -1
    # Threshold for Low Severity Vulnerabilities
    cxLow: # optional, default is -1
    # Saves a comment with the scan results. For example -comment important scan.
    cxComment: # optional, default is 
    # Force scan on source code, which has not been changed since the last scan of the same project. (Not compatible with -Incremental option.)
    cxForceScan: # optional
    # Run incremental scan instead of a full scan.
    cxIncremental: # optional
    # Comma separated list of folder name patterns to exclude from scan. For example, exclude all test and log folders: -locationPathExclude test*,log_*
    cxExcludeFolders: # optional, default is 
    # Comma separated list of file name patterns to exclude from scan. For example, exclude all files with .class extension: -locationFilesExclude *.class
    cxExcludeFiles: # optional, default is 
    # Code language configuration. Possible values are : Default Configuration, Japanese (Shift-JIS). If configuration is not set, Default Configuration is used.
    cxConfiguration: # optional, default is Default Configuration
    # Scan will not be visible to other users.
    cxPrivate: # optional
    # SAST Scan Report in XML format
    cxReportXML: # optional, default is 
    # SAST Scan Report in PDF format
    cxReportPDF: # optional, default is 
    # SAST Scan Report in RTF format
    cxReportRTF: # optional, default is 
    # SAST Scan Report in CSV format
    cxReportCSV: # optional, default is 
    # Log file to be created.
    cxLog: # optional, default is 
    # Turns on verbose mode. All messages and events will be sent to the console or log file.
    cxVerbose: # optional, default is true
    # OSA high severity vulnerability threshold. If the number of high vulnerabilities exceeds the threshold, scan will end with an error (see Error/Exit Codes).
    cxOsaHigh: # optional, default is -1
    # OSA medium severity vulnerability threshold. If the number of medium vulnerabilities exceeds the threshold, scan will end with an error (see Error/Exit Codes).
    cxOsaMedium: # optional, default is -1
    # OSA low severity vulnerability threshold. If the number of high vulnerabilities exceeds the threshold, scan will end with an error (see Error/Exit Codes).
    cxOsaLow: # optional, default is -1
    # Local or network path to sources or source repository branch. May include multiple list of folders (local or shared) separated by comma.
    cxOsaLocationPath: # optional, default is 
    # Comma separated list of file extensions to extract in the OSA scan. For example: -OsaArchiveToExtract *.zip extracts only files with .zip extension.
    cxOsaArchiveToExtract: # optional, default is 
    # Comma separated list of file name patterns to exclude from the OSA scan. For example: *.dll will include only dll files.
    cxOsaFilesInclude: # optional, default is 
    # Comma separated list of file name patterns to exclude from the OSA scan. Exclude extensions by using *.<extension>, or exclude files by using */<file>. Examples: -OsaFilesExclude *.class excludes all files which start with the .class. Examples: -OsaFilesExclude */plexus-utils-1.5.6.jar excludes all files which start with plexus-utils-1.5.6.jar.
    cxOsaFilesExclude: # optional, default is 
    # Comma separated list of folder path patterns to exclude from the OSA scan. For example: -OsaPathExclude test excludes all folders which start with test prefix.
    cxOsaPathExclude: # optional, default is 
    # Generate CxOSA HTML report.
    cxOsaReportHtml: # optional, default is 
    # Generate CxOSA PDF report.
    cxOsaReportPDF: # optional, default is 
    # Extraction depth of files to include in the OSA scan.
    cxOsaDepth: # optional, default is 
    # Retrieve all supported package dependencies before performing OSA scan (see Remarks section).
    cxExecutePackageDependency: # optional
    # Generate CxOSA JSON report.
    cxOsaJson: # optional, default is 
    # SCA Username
    cxScaUsername: # optional, default is 
    # SCA Password
    cxScaPassword: # optional, default is 
    # SCA Account Name
    cxScaAccount: # optional, default is 
    # SCA API URL
    cxScaApiUrl: # optional, default is 
    # SCA Access Control URL
    cxScaAcessControlUrl: # optional, default is 
    # SCA Web App URL
    cxScaWebAppUrl: # optional, default is 
    # SCA High Threshold
    cxScaHigh: # optional, default is -1
    # SCA Medium Threshold
    cxScaMedium: # optional, default is -1
    # SCA Low Threshold
    cxScaLow: # optional, default is -1
    # SCA Location Path
    cxScaLocationPath: # optional, default is 
    # SCA Files Include
    cxScaFilesInclude: # optional, default is 
    # SCA Files Exclude
    cxScaFilesExclude: # optional, default is 
    # SCA Folders Exclude
    cxScaPathExclude: # optional, default is 
    # This parameter will break the build if the CxOSA policy is violated.
    cxCheckPolicy: # optional
    # Skip Checkmarx Action Step if Fail
    cxSkipIfFail: # optional
    # Trust Self-signed Certificates
    cxTrustedCertificates: # optional
    # Github Token Secret
    cxGithubToken: # optional, default is 
    # Create Github Issues
    cxGithubIssues: # optional
    # Github Labels for Issues created
    cxGithubLabels: # optional, default is bug
    # Github Assignees for Issues created
    cxGithubAssignees: # optional, default is 
    # Github Milestone for Issues created
    cxGithubMilestone: # optional
      
